name: mosque_donation_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  sizer:
  modal_progress_hud_nsn: ^0.5.1
  http: ^0.13.4
  provider: ^6.0.3
  fluttertoast: ^8.0.8
  intl:
  carousel_slider: ^5.0.0
  mek_stripe_terminal: ^3.7.0
  permission_handler: ^11.3.1
  flutter_dotenv:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/.env
  - assets/images/


  fonts:
  - family: Poppins
    fonts:
    - asset: assets/fonts/Poppins-Thin.ttf
      weight: 100
    - asset: assets/fonts/Poppins-Light.ttf
      weight: 200
    - asset: assets/fonts/Poppins-Medium.ttf
      weight: 300
    - asset: assets/fonts/Poppins-Regular.ttf
      weight: 400
    - asset: assets/fonts/Poppins-Bold.ttf
      weight: 500
    - asset: assets/fonts/Poppins-ExtraBold.ttf
      weight: 600
    - asset: assets/fonts/Poppins-BoldItalic.ttf
      weight: 700
